@hostname = localhost
@port = 3001
@personId = 600077ca9de68446c8504aa5
@missingPersonId = 5fb785cef6d8eb20a092c20d
@host = http://{{hostname}}:{{port}}

###

GET {{host}}/api/persons/{{personId}} HTTP/1.1
Accept: application/json

###

GET {{host}}/api/persons/{{missingPersonId}} HTTP/1.1
Accept: application/json